## Python 102

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

In [62]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry\'s']
costs = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]

In [7]:
print("I need to buy:")
for item in items:
    print('\t-',item)

I need to buy:
	- cheese
	- whole milk
	- kefir
	- tofu four-pack
	- kale
	- oranges
	- ham
	- ben & jerry's


Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

In [19]:
print("I need to buy: ")
for item in items:
    print("\t- [ ]",item)

I need to buy: 
	- [ ] cheese
	- [ ] whole milk
	- [ ] kefir
	- [ ] tofu four-pack
	- [ ] kale
	- [ ] oranges
	- [ ] ham
	- [ ] ben & jerry's


In [26]:
print("I need to buy: ")
for item,cost in zip(items,costs):
    print("\t- [ ] ",item,' $',cost,sep='')

I need to buy: 
	- [ ] cheese $2.79
	- [ ] whole milk $3.42
	- [ ] kefir $4.5
	- [ ] tofu four-pack $12.0
	- [ ] kale $2.75
	- [ ] oranges $3.64
	- [ ] ham $25.0
	- [ ] ben & jerry's $5.29


In [63]:
x = (zip(items,costs)) # zip is another type
grocery_dict = dict(x) # can be fed to dictionary
grocery_dict.keys()

dict_keys(['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', "ben & jerry's"])

In [41]:
# Another way to print this list
print('I need to buy:')
for x,y in grocery_dict.items():
    print("\t- [ ] ",x,' ($',cost,')',sep='')

I need to buy:
	- [ ] cheese ($5.29)
	- [ ] whole milk ($5.29)
	- [ ] kefir ($5.29)
	- [ ] tofu four-pack ($5.29)
	- [ ] kale ($5.29)
	- [ ] oranges ($5.29)
	- [ ] ham ($5.29)
	- [ ] ben & jerry's ($5.29)


So let's now add the total grocery bill at the end:

In [43]:
print('The total is $',sum(grocery_dict.values()),sep='')

The total is $59.39


Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [47]:
i = 1
while i < 6:
    print(i)
    i += 1

1
2
3
4
5


- What is break and continue?
- Are they different? How?
- Run the following code:

In [57]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        print("foo")
        continue # continue allows exceptional results to a loop, but allows it to pass over the rest of loop
    print(i)
    
# this doesn't seem like that good of an example of continue because this is an else condition. 
# does it help you avoid some deeply nested loops? 

1
2
foo
4
5
6


How does the code above work?

Now run this code:

In [ ]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        print("foo")
        break
    print(i)

Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [73]:
total = 0
for key,val in grocery_dict.items():
    if total + val > 25:
        break
    else:
        total += val
print('The total is $',total,sep='')

The total is $22.71


What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

In [79]:
limit = 10;
print('For under $',limit,' I can buy:',sep='')
for key,val in grocery_dict.items():
    if val < limit:
        print(key,' ($',val,')',sep='')

For under $10 I can buy:
cheese ($2.79)
whole milk ($3.42)
kefir ($4.5)
kale ($2.75)
oranges ($3.64)
ben & jerry's ($5.29)


### Nested Loops

In [3]:
list2 = [1,2,3,4,5]

for x in list2:
    print('loop1:', x)
    for y in list2:
        print('loop2---', y)

loop1: 1
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 2
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 3
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 4
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 5
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [182]:
not(12%6)

True

In [80]:
i = 2 # dividened (also the number we are checking to see if it's a prime)
while(i < 100): # test values up to 100
    j = 2 # divisor (increases by 1)
    while(j <= (i/j)):# while there are bigger factors out there...
        if not(i%j): break # and as long as i is not a multiple of j (if so break out of the while loop and jump to i = i + 1 (i.e. skip j iterations, skip prime alert))
        j = j + 1 # keep increasing j to find the bigger factors
    if (j > i/j) : print( i, " is prime")# if the final j of this round is larger than the quotient thus far, it has not been divided out thus must be prime
    i = i + 1 # increase the counter

print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [81]:
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [111]:
x = shopping_dict['Grocieries']
print(x.values())


dict_values([5.29, 2.79, 25.0, 2.75, 4.5, 3.64, 12.0, 3.42])


In [147]:
print("I need to buy items, in the follow categories:")
total = 0
for cat,list in shopping_dict.items():
    cat_total = 0
    print('\t',cat,':',sep='')
    #print(list)
    for items,values in list.items():
        cat_total += values
        print('\t\t',items,' - $',values,sep = '')        
        total += values
    print('\tThe category total is $%.2f'%cat_total,'\n')
print('The total is $%.2f'%total)

I need to buy items, in the follow categories:
	Grocieries:
		ben & jerrys - $5.29
		cheese - $2.79
		ham - $25.0
		kale - $2.75
		kefir - $4.5
		oranges - $3.64
		tofu four-pack - $12.0
		whole milk - $3.42
	The category total is $59.39 

	House supplies:
		toilet paper pack - $16.5
		clorox spray - $6.43
		kleenex - $2.5
	The category total is $25.43 

	Pet supplies:
		Taste of the Wild - $65.2
		squeaky toy - $4.5
		duck feet - $8.45
	The category total is $78.15 

The total is $162.97


In [163]:
# But make it a function
def shoppingListPrint(argument):
    total = 0
    for cat,list in argument.items():
        cat_total = 0
        print('\t',cat,':',sep='')
        #print(list)
        for items,values in list.items():
            cat_total += values
            print('\t\t',items,' - $',values,sep = '')        
            total += values
        print('\tThe category total is $%.2f'%cat_total,'\n')
    print('The total is $%.2f'%total)
    
shoppingListPrint(shopping_dict)

	Grocieries:
		ben & jerrys - $5.29
		cheese - $2.79
		ham - $25.0
		kale - $2.75
		kefir - $4.5
		oranges - $3.64
		tofu four-pack - $12.0
		whole milk - $3.42
	The category total is $59.39 

	House supplies:
		toilet paper pack - $16.5
		clorox spray - $6.43
		kleenex - $2.5
	The category total is $25.43 

	Pet supplies:
		Taste of the Wild - $65.2
		squeaky toy - $4.5
		duck feet - $8.45
	The category total is $78.15 

The total is $162.97


### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

In [150]:
def sayHello():
    print("Hello!")
    
sayHello()

Hello!


In [152]:
def shout(phrase):
    print(phrase + "!!!")
    
shout("oh hai")

oh hai!!!


What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

In [177]:
shout() # very helpfully formats the error to the function's argument as defined in the script ('phrase')

TypeError: shout() missing 1 required positional argument: 'phrase'

What if we wanted to run a function, take its output and put it in to another function?

```
def add_one(number):
  return number + 1

def times_five(number):
  return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)
```

What will the above code return?

In [153]:
def add_one(number):
    return number + 1 # passes it on to the calling script, can set a value to a variable (output)

def times_five(number):
    return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)

10


Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

In [160]:
def add_one_two(number):
    return number + 1, number + 2  # passes more than one answer through

six, seven =add_one_two(5)
print(six)
print(seven)

# or 

vector_of_six_seven = add_one_two(5)
print(vector_of_six_seven)

6
7
(6, 7)


### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [176]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]

def mean(list):
    total = 0
    for number in samp_list:
        total += number
    print('{0:.2f}'.format(total/len(samp_list)))
    #return(total/len(samp_list))

mean(samp_list)

6.36


### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart

## Jupyter Bonus

This doesn't really fit in with the rest of Python 102, but Jupyter is incredibly flexible! Here are two examples of embedding beautiful LaTex scripting in a notebook.

In [178]:
%%latex # this will make the entire cell LaTeX syntax
$$\lim\limits_{x \to \infty} \exp(-x) = 0$$

<IPython.core.display.Latex object>

In [2]:
from IPython.display import Math
# this imports a function called Math() in which you can pass in a raw string of LaTeX
Math('F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx')

<IPython.core.display.Math object>